# Generated by Django 4.2.19 on 2025-03-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0004_initial'),
        ('page', '0006_alter_mnemonic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_message', models.CharField(max_length=200)),
                ('red_high', models.FloatField(null=True)),
                ('yellow_high', models.FloatField(null=True)),
                ('yellow_low', models.FloatField(null=True)),
                ('red_low', models.FloatField(null=True)),
                ('mission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mission')),
                ('mnemonic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms_by_id', to='page.mnemonic')),
                ('mnemonic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms_by_name', to='page.mnemonic', to_field='name')),
            ],
        ),
    ]
