# Generated by Django 5.1.6 on 2025-02-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mnemonic',
            name='name',
            field=models.CharField(default='noName', max_length=200),
        ),
    ]
