# Generated by Django 4.2.19 on 2025-02-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_mnemonic_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mnemonic',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageHasMnemonic',
        ),
    ]
