# Generated by Django 4.2.19 on 2025-02-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_delete_mnemonic_delete_page_delete_pagehasmnemonic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection_Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mission_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('protocol', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=16)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
