# Generated by Django 4.2.19 on 2025-03-28 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mnemonic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('name', models.CharField(default='noName', max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PageMnemonic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('mnemonic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.mnemonic')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnemonics', to='page.page')),
            ],
            options={
                'unique_together': {('page', 'position')},
            },
        ),
    ]
