# Generated by Django 4.2.19 on 2025-02-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagehasmnemonic',
            name='mnemonicId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagehasmnemonic',
            name='pageId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
