# Generated by Django 4.2.19 on 2025-02-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_pagehasmnemonic_mnemonicid_pagehasmnemonic_pageid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageHasMnemonic',
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic1',
            field=models.ManyToManyField(default=None, related_name='page_mnemonic1', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic10',
            field=models.ManyToManyField(default=None, related_name='page_mnemonic10', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic11',
            field=models.ManyToManyField(default=None, related_name='page_mnemonic11', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic12',
            field=models.ManyToManyField(default=None, related_name='page_mnemonic12', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic2',
            field=models.ManyToManyField(default=None, related_name='page_mnemonic2', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic3',
            field=models.ManyToManyField(default=None, related_name='page_mnemonic3', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic4',
            field=models.ManyToManyField(default=None, related_name='page_mnemonic4', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic5',
            field=models.ManyToManyField(default=None, related_name='page_mnemonic5', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic6',
            field=models.ManyToManyField(default=None, related_name='page_mnemonic6', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic7',
            field=models.ManyToManyField(default=None, related_name='page_mnemonic7', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic8',
            field=models.ManyToManyField(default=None, related_name='page_mnemonic8', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic9',
            field=models.ManyToManyField(default=None, related_name='page_mnemonic9', to='page.mnemonic'),
        ),
    ]
