# Generated by Django 4.2.19 on 2025-02-22 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_delete_pagehasmnemonic_page_mnemonic1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic1',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic10',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic11',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic12',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic2',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic3',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic4',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic5',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic6',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic7',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic8',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic9',
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_mnemonic1', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_mnemonic10', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_mnemonic11', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_mnemonic12', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_mnemonic2', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_mnemonic3', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_mnemonic4', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_mnemonic5', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_mnemonic6', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_mnemonic7', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_mnemonic8', to='page.mnemonic'),
        ),
        migrations.AddField(
            model_name='page',
            name='Mnemonic9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_mnemonic9', to='page.mnemonic'),
        ),
    ]
