# Generated by Django 4.2.19 on 2025-02-22 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_remove_page_mnemonic1_remove_page_mnemonic10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic1',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic10',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic11',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic12',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic2',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic3',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic4',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic5',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic6',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic7',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic8',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Mnemonic9',
        ),
        migrations.CreateModel(
            name='PageMnemonic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('mnemonic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.mnemonic')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnemonics', to='page.page')),
            ],
            options={
                'unique_together': {('page', 'position')},
            },
        ),
    ]
