# Generated by Django 4.2.19 on 2025-05-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_remove_page_mnemonic1_remove_page_mnemonic10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('encoding_type', models.CharField(choices=[('ASCII', 'ASCII'), ('Binary', 'Binary')], default='ASCII', max_length=10)),
                ('ascii_content', models.TextField(blank=True, null=True)),
                ('binary_content', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
