# Generated by Django 4.2.19 on 2025-03-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_remove_page_mnemonic1_remove_page_mnemonic10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnemonic',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
