# Generated by Django 4.2.19 on 2025-05-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='name',
            field=models.CharField(default='noName', max_length=200),
        ),
    ]
