# Generated by Django 4.2.19 on 2025-08-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_command_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='parameters',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
